services:
  web:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules/
  app:
    build: ./backend
    hostname: app
    ports:
      - 8080:8080
    networks:
      - redis
  db:
    image: redis:latest
    restart: always
    hostname: db
    ports:
      - 6379:6379
    networks:
      redis:
        aliases:
          - db
networks:
  redis:
    name: redis
